name: 'TooNovel-DataScraper'


on:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Remove Chrome
      run: sudo apt purge google-chrome-stable

    - name: Remove default Chromium
      run: sudo apt purge chromium-browser

    - name: Install a new Chromium
      run: sudo apt install -y chromium-browser

    - name: Run main.py
      run: |
        python recentMunpiaCrawler.py
        python recentPageCrawlerTest.py
        python recentSeriesCrawler.py
        
    - name: Get Github Actions IP
      id: ip
      uses: haythem/public-ip@v1.2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        
    - name: Add Github Actions IP to Security group
      run: |
        aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port ${{ secrets.DB_PORT }} --cidr ${{ steps.ip.outputs.ipv4 }}/32

    - name: Run recentDBInsert.py
      run: |
        python recentDBInsert.py
      env:
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_URL: ${{ secrets.DB_URL }}
        DB_PORT: ${{ secrets.DB_PORT }}
        
    - name: Remove Github Actions IP From Security Group
      run: |
        aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port ${{ secrets.DB_PORT }} --cidr ${{ steps.ip.outputs.ipv4 }}/32
